name: paperless-ngx
services:
  paperless-ngx:
    cpu_shares: 90
    command: []
    container_name: paperless-ngx
    depends_on:
      paperless-ngx-broker:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 3732M
    environment:
      - COMPOSE_PROJECT_NAME=paperless-ngx
      - PAPERLESS_ADMIN_PASSWORD=klajee12
      - PAPERLESS_ADMIN_USER=ukhan
      - PAPERLESS_OCR_LANGUAGE=eng
      - PAPERLESS_REDIS=redis://paperless-ngx-broker:6379
      - PAPERLESS_TASK_WORKERS=2
      - PAPERLESS_THREADS_PER_WORKER=1
      - PAPERLESS_TIKA_ENABLED=true
      - PAPERLESS_TIKA_ENDPOINT=http://paperless-ngx-tika:9998
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://paperless-ngx-gotenberg:3000
      - PAPERLESS_TIME_ZONE=Europe/Istanbul
      - PAPERLESS_URL=http://192.168.1.6:8000
      - USERMAP_GID= 1000
      - USERMAP_UID= 1000
    hostname: paperless-ngx
    image: ghcr.io/paperless-ngx/paperless-ngx:2.13.4
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless.png
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/radxa128gb/AppData/paperless-ngx/paperless_data
        target: /usr/src/paperless/data
        bind:
          create_host_path: true
      - type: bind
        source: /media/radxa128gb/AppData/paperless-ngx/paperless_media
        target: /usr/src/paperless/media
        bind:
          create_host_path: true
      - type: bind
        source: /media/radxa128gb/AppData/paperless-ngx/paperless_export
        target: /usr/src/paperless/export
        bind:
          create_host_path: true
      - type: bind
        source: /media/radxa128gb/AppData/paperless-ngx/paperless_consume
        target: /usr/src/paperless/consume
        bind:
          create_host_path: true
      - type: bind
        source: /media/radxa128gb
        target: /media/radxa128gb
    devices: []
    cap_add: []
    networks:
      - paperless-ngx
    privileged: false
  paperless-ngx-broker:
    cpu_shares: 90
    command: []
    container_name: paperless-ngx-broker
    deploy:
      resources:
        limits:
          memory: 3732M
    hostname: paperless-ngx-broker
    image: docker.io/library/redis:7.2-alpine
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/radxa128gb/AppData/paperless-ngx/redis
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /media/radxa128gb
        target: /media/radxa128gb
    ports: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - paperless-ngx
    privileged: false
  paperless-ngx-gotenberg:
    cpu_shares: 90
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
    container_name: paperless-ngx-gotenberg
    deploy:
      resources:
        limits:
          memory: 3732M
    hostname: paperless-ngx-gotenberg
    image: docker.io/gotenberg/gotenberg:8.7
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/radxa128gb
        target: /media/radxa128gb
    ports: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - paperless-ngx
    privileged: false
  paperless-ngx-tika:
    cpu_shares: 90
    command: []
    container_name: paperless-ngx-tika
    deploy:
      resources:
        limits:
          memory: 3732M
    hostname: paperless-ngx-tika
    image: ghcr.io/paperless-ngx/tika:2.9.1-minimal
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/radxa128gb
        target: /media/radxa128gb
    ports: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - paperless-ngx
    privileged: false
networks:
  paperless-ngx:
    name: paperless-ngx
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Paperless-ngx is a community-supported open-source document management
      system that transforms your physical documents into a searchable online
      archive so you can keep, well, less paper.
  developer: paperless-ngx
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless.png
  index: /
  is_uncontrolled: false
  main: paperless-ngx
  port_map: "8000"
  scheme: http
  store_app_id: paperless-ngx
  tagline:
    en_us: Paperless-ngx
  thumbnail: ""
  tips:
    before_install:
      en_us: >
        Read this before installing:
        https://community.bigbeartechworld.com/t/added-paperlessngx-to-bigbearcasaos/1954#p-3625-documentation-4
  title:
    custom: ""
    en_us: Paperless-ngx
