name: stirling-pdf
services:
  app:
    cpu_shares: 90
    command: []
    container_name: stirlingpdf
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - APP_HOME_NAME=Stirling PDF
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
    image: frooodle/s-pdf:latest
    labels:
      icon: https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/docs/stirling.png
    ports:
      - target: 8080
        published: "9090"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/stirling/configs
        target: /configs
      - type: bind
        source: /DATA/AppData/stirling/logs
        target: /logs
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    hostname: stirlingpdf
x-casaos:
  architectures:
    - amd64
    - arm64
  author: WisdomSky
  category: Coolstore
  description:
    en_us: Stirling-PDF is a locally hosted web application that allows you to
      perform various operations on PDF files, such as splitting and adding
      images.
  developer: Frooodle
  hostname: ""
  icon: https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/docs/stirling.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: "9090"
  scheme: http
  screenshot_link:
    - https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/images/stirling-home.png
  store_app_id: stirling-pdf
  tagline:
    en_us: Stirling-PDF is a locally hosted web application that allows you to
      perform various operations on PDF files, such as splitting and adding
      images.
  thumbnail: https://raw.githubusercontent.com/Frooodle/Stirling-PDF/main/docs/stirling.png
  title:
    custom: ""
    en_us: Stirling PDF
